name: Build DriverMate PH APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK manually
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version

      - name: Install Gradle
        run: |
          sudo apt-get install -y gradle
          gradle -v

      - name: Build debug APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DriverMatePH-debug-apk
          path: app/build/outputs/apk/debug/*.apk
